name: test

on: [push, workflow_dispatch]

jobs:
  build:
    name: Tests
    timeout-minutes: 10
    defaults:
      run:
        shell: bash

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Check environment
      run: |
        docker version
        docker buildx version
        docker info
        cat /proc/cpuinfo
        free
        lsb_release -a
        cat /etc/docker/daemon.json

    - name: Build php container
      run: docker build -t redistest .

    - name: Pull redis container
      run: docker pull redis:7.2-alpine

    - name: Docker ps
      run: docker ps

    - name: Test redis with network host
      run: |
        docker run --rm --network host --name redis -d redis:7.2-alpine
        sleep 5
        time docker run --rm --network host -v$(pwd):/var/www redistest php test.php
        docker stop redis

    - name: Docker ps
      run: docker ps

    - name: Disable userland proxy in docker daemon
      run: |
        sudo jq '.+{"userland-proxy":false}' /etc/docker/daemon.json > /tmp/daemon.json
        sudo mv /tmp/daemon.json /etc/docker/daemon.json
        sudo systemctl restart docker.service

    - name: Test redis with bridged network and docker proxy disabled
      run: |
        docker run --rm --name redis -d -p 6379:6379 redis:7.2-alpine
        sleep 5
        time docker run --rm --network host -v$(pwd):/var/www redistest php test.php
        docker stop redis

    - name: Enable userland proxy in docker daemon
      run: |
        sudo jq '.+{"userland-proxy":true}' /etc/docker/daemon.json > /tmp/daemon.json
        sudo mv /tmp/daemon.json /etc/docker/daemon.json
        sudo systemctl restart docker.service

    - name: Test redis with docker proxy (timeout error)
      run: |
        docker run --rm --name redis -d -p 6379:6379 redis:7.2-alpine
        sleep 5
        time docker run --rm --network host -v$(pwd):/var/www redistest php test.php
        docker stop redis
